apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:clouddrove/argocd-k8s-addons.git
      targetRevision: feat/labels
      path: charts/helmchart
      helm:
        valueFiles:
          - $values/overrr.yaml
        values: |
          ingressNginx:
            enable: false
    - repoURL: https://github.com/NotMaharshi/addons-override.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
